room_name = [
"Huge Redwood Forest", "Creeper Forest", "Violet Forest", "Marvelous Forest",
"Pacific Bear Wood", "Speckled Warthog Timberland", "Brichill Woodland", "Galnet Wood",
"Baxbron Timberland", "Carigshall Grove", "Threatening Olive Timberland", 
"Wicked Loch Forest", "Quiet Forest", "Fancy Forest", "Wild Porcupine Grove",
"Collared Toad Woods", "Gloustead Covert", "Weyrior Forest", "Sutberg Timberland",
"Sagtara Wood", "Faded Palm Woods", "Hypnotic Pine Woods", "Beautiful Grove",
"Panoramic Woodland", "Black Mouse Covert", "Snow Leopard Wood", "Brighsevain Woods",
"Emerway Woodland", "Bradher Forest", "Plaincord Thicket", "Spotless Redwood Grove",
"Heavenly Hill Covert", "Lonely Thicket", "Gigantic Woods", "Oriental Hawk Woods",
"Savanna Wolverine Wood", "Carbrook Thicket", "Grimfield Forest", "Reidnigan Grove",
"Amesmore Grove", "Frightened Wetland Wood", "Puny Quagmire Thicket", "Giant Grove",
"Mighty Wood", "Grand Duck Wilds", "Alpine Porcupine Forest", "Stanter Wilds",
"Atidover Timberland", "Bredendare Grove", "Notgue Grove",
"Huge Redwood Forest", "Creeper Forest", "Violet Forest", "Marvelous Forest",
"Pacific Bear Wood", "Speckled Warthog Timberland", "Brichill Woodland", "Galnet Wood",
"Baxbron Timberland", "Carigshall Grove", "Threatening Olive Timberland", 
"Wicked Loch Forest", "Quiet Forest", "Fancy Forest", "Wild Porcupine Grove",
"Collared Toad Woods", "Gloustead Covert", "Weyrior Forest", "Sutberg Timberland",
"Sagtara Wood", "Faded Palm Woods", "Hypnotic Pine Woods", "Beautiful Grove",
"Panoramic Woodland", "Black Mouse Covert", "Snow Leopard Wood", "Brighsevain Woods",
"Emerway Woodland", "Bradher Forest", "Plaincord Thicket", "Spotless Redwood Grove",
"Heavenly Hill Covert", "Lonely Thicket", "Gigantic Woods", "Oriental Hawk Woods",
"Savanna Wolverine Wood", "Carbrook Thicket", "Grimfield Forest", "Reidnigan Grove",
"Amesmore Grove", "Frightened Wetland Wood", "Puny Quagmire Thicket", "Giant Grove",
"Mighty Wood", "Grand Duck Wilds", "Alpine Porcupine Forest", "Stanter Wilds",
"Atidover Timberland", "Bredendare Grove", "Rpitas Grove"
]

room_description = [
  "The forest was small, dense, and verdant. Its canopy was reigned by magnolia, hazel, and sequoia, and sparkling light dancing between the branches allowed for vibrant shrubs to take advantage of the moss covered grounds below. The only opening is to the east or back west.",
  "Bundled creepers drooped from the occasional tree, and a range of flowers, which grew all over the place, contrasted against the otherwise brown and green terrain. The only opening is to the east or back west.", 
  "Thick tree limbs grasped many trees, and a variety of flowers, which grew in a sprinkled and disorderly fashion, spruced up the otherwise dark lower level. The only opening is to the east or west.",
  "A hodgepodge of wild sounds, belonging mostly to foraging animals, reverberated through the air, and formed a chaotic orchestra with the swaying of tree tops in the wind. The only opening is still to the east or west.",
  "The forest was colossal, impenetrable, and flourishing. Its canopy was ruled by hazel, juniper, and buxus, and abundant dancing lights bounced through their crowns for a flood of ferns to dominate the sloping and slanting ground below. You can only continue eastwards or back westwards.",
  "Swooping vines hung from every tree, and a variety of flowers, which desperately tried to avoid the shadows, highlighted the otherwise unvarying scenery. Why can I only go east or west?", 
  "A mixture of animal noises, most belonged to critters, added life to the forest, and drowned out the occasional roar of a large animal trying to scare away predators. Only path lies eastwards or westwards.",
  "The forest was huge, spacious, and rich. Its canopy was eclipsed by spruce, magnolia, and larch, and abundant dancing lights bounced through their crowns for a medley of herbs to grow in the moist and fertile bottom layer below. Once again, the only directions available are east or west.", 
  "Thick tree limbs grasped many trees, and a variety of flowers, which grew in a sprinkled and disorderly fashion, spruced up the otherwise dark lower level. Once again, you can only continue east or west.", 
  "A discord of wild noises, belonging mostly to prowling animals, resonated through the air, and added to the sounds of the rustling of the leaves and branches of the tree tops in the wind. Finally you can go in a different direction, to the north.",
  "The forest was small, dense, and verdant. Its canopy was reigned by magnolia, hazel, and sequoia, and sparkling light dancing between the branches allowed for vibrant shrubs to take advantage of the moss covered grounds below. The only opening is to the west or back south to where you just came from.",
  "Bundled creepers drooped from the occasional tree, and a range of flowers, which grew all over the place, contrasted against the otherwise brown and green terrain. The only way forward is to the west.", 
  "Thick tree limbs grasped many trees, and a variety of flowers, which grew in a sprinkled and disorderly fashion, spruced up the otherwise dark lower level. The only opening ahead is to the west or back east.",
  "A hodgepodge of wild sounds, belonging mostly to foraging animals, reverberated through the air, and formed a chaotic orchestra with the swaying of tree tops in the wind. The only opening is still to the west or back east.",
  "The forest was colossal, impenetrable, and flourishing. Its canopy was ruled by hazel, juniper, and buxus, and abundant dancing lights bounced through their crowns for a flood of ferns to dominate the sloping and slanting ground below. You can only continue west or east.",
  "Swooping vines hung from every tree, and a variety of flowers, which desperately tried to avoid the shadows, highlighted the otherwise unvarying scenery. Why can I only go west or back east?", 
  "A mixture of animal noises, most belonged to critters, added life to the forest, and drowned out the occasional roar of a large animal trying to scare away predators. Only path lies westwards and eastwards.",
  "The forest was huge, spacious, and rich. Its canopy was eclipsed by spruce, magnolia, and larch, and abundant dancing lights bounced through their crowns for a medley of herbs to grow in the moist and fertile bottom layer below. West is the only way available forward to you.", 
  "Thick tree limbs grasped many trees, and a variety of flowers, which grew in a sprinkled and disorderly fashion, spruced up the otherwise dark lower level. Once again, you can only continue ahead to the west.", 
  "A discord of wild noises, belonging mostly to prowling animals, resonated through the air, and added to the sounds of the rustling of the leaves and branches of the tree tops in the wind. Finally you can go in a different direction, to the north.",
  "The forest was small, dense, and verdant. Its canopy was reigned by magnolia, hazel, and sequoia, and sparkling light dancing between the branches allowed for vibrant shrubs to take advantage of the moss covered grounds below. The only opening is to the east or back west.",
  "Bundled creepers drooped from the occasional tree, and a range of flowers, which grew all over the place, contrasted against the otherwise brown and green terrain. The only opening is to the east or back west.", 
  "Thick tree limbs grasped many trees, and a variety of flowers, which grew in a sprinkled and disorderly fashion, spruced up the otherwise dark lower level. The only opening is to the east or west.",
  "A hodgepodge of wild sounds, belonging mostly to foraging animals, reverberated through the air, and formed a chaotic orchestra with the swaying of tree tops in the wind. The only opening is still to the east or west.",
  "The forest was colossal, impenetrable, and flourishing. Its canopy was ruled by hazel, juniper, and buxus, and abundant dancing lights bounced through their crowns for a flood of ferns to dominate the sloping and slanting ground below. You can only continue eastwards or back westwards.",
  "Swooping vines hung from every tree, and a variety of flowers, which desperately tried to avoid the shadows, highlighted the otherwise unvarying scenery. Why can I only go east or west?", 
  "A mixture of animal noises, most belonged to critters, added life to the forest, and drowned out the occasional roar of a large animal trying to scare away predators. Only path lies eastwards or westwards.",
  "The forest was huge, spacious, and rich. Its canopy was eclipsed by spruce, magnolia, and larch, and abundant dancing lights bounced through their crowns for a medley of herbs to grow in the moist and fertile bottom layer below. Once again, the only directions available are east or west.", 
  "Thick tree limbs grasped many trees, and a variety of flowers, which grew in a sprinkled and disorderly fashion, spruced up the otherwise dark lower level. Once again, you can only continue east or west.", 
  "A discord of wild noises, belonging mostly to prowling animals, resonated through the air, and added to the sounds of the rustling of the leaves and branches of the tree tops in the wind. Finally you can go in a different direction, to the north.",
  "The forest was small, dense, and verdant. Its canopy was reigned by magnolia, hazel, and sequoia, and sparkling light dancing between the branches allowed for vibrant shrubs to take advantage of the moss covered grounds below. The only opening is to the west or back south to where you just came from.",
  "Bundled creepers drooped from the occasional tree, and a range of flowers, which grew all over the place, contrasted against the otherwise brown and green terrain. The only way forward is to the west.", 
  "Thick tree limbs grasped many trees, and a variety of flowers, which grew in a sprinkled and disorderly fashion, spruced up the otherwise dark lower level. The only opening ahead is to the west or back east.",
  "A hodgepodge of wild sounds, belonging mostly to foraging animals, reverberated through the air, and formed a chaotic orchestra with the swaying of tree tops in the wind. The only opening is still to the west or back east.",
  "The forest was colossal, impenetrable, and flourishing. Its canopy was ruled by hazel, juniper, and buxus, and abundant dancing lights bounced through their crowns for a flood of ferns to dominate the sloping and slanting ground below. You can only continue west or east.",
  "Swooping vines hung from every tree, and a variety of flowers, which desperately tried to avoid the shadows, highlighted the otherwise unvarying scenery. Why can I only go west or back east?", 
  "A mixture of animal noises, most belonged to critters, added life to the forest, and drowned out the occasional roar of a large animal trying to scare away predators. Only path lies westwards and eastwards.",
  "The forest was huge, spacious, and rich. Its canopy was eclipsed by spruce, magnolia, and larch, and abundant dancing lights bounced through their crowns for a medley of herbs to grow in the moist and fertile bottom layer below. West is the only way available forward to you.", 
  "Thick tree limbs grasped many trees, and a variety of flowers, which grew in a sprinkled and disorderly fashion, spruced up the otherwise dark lower level. Once again, you can only continue ahead to the west.", 
  "A discord of wild noises, belonging mostly to prowling animals, resonated through the air, and added to the sounds of the rustling of the leaves and branches of the tree tops in the wind. Finally you can go in a different direction, to the north.",
  "The forest was small, dense, and verdant. Its canopy was reigned by magnolia, hazel, and sequoia, and sparkling light dancing between the branches allowed for vibrant shrubs to take advantage of the moss covered grounds below. The only opening is to the east or back west.",
  "Bundled creepers drooped from the occasional tree, and a range of flowers, which grew all over the place, contrasted against the otherwise brown and green terrain. The only opening is to the east or back west.", 
  "Thick tree limbs grasped many trees, and a variety of flowers, which grew in a sprinkled and disorderly fashion, spruced up the otherwise dark lower level. The only opening is to the east or west.",
  "A hodgepodge of wild sounds, belonging mostly to foraging animals, reverberated through the air, and formed a chaotic orchestra with the swaying of tree tops in the wind. The only opening is still to the east or west.",
  "The forest was colossal, impenetrable, and flourishing. Its canopy was ruled by hazel, juniper, and buxus, and abundant dancing lights bounced through their crowns for a flood of ferns to dominate the sloping and slanting ground below. You can only continue eastwards or back westwards.",
  "Swooping vines hung from every tree, and a variety of flowers, which desperately tried to avoid the shadows, highlighted the otherwise unvarying scenery. Why can I only go east or west?", 
  "A mixture of animal noises, most belonged to critters, added life to the forest, and drowned out the occasional roar of a large animal trying to scare away predators. Only path lies eastwards or westwards.",
  "The forest was huge, spacious, and rich. Its canopy was eclipsed by spruce, magnolia, and larch, and abundant dancing lights bounced through their crowns for a medley of herbs to grow in the moist and fertile bottom layer below. Once again, the only directions available are east or west.", 
  "Thick tree limbs grasped many trees, and a variety of flowers, which grew in a sprinkled and disorderly fashion, spruced up the otherwise dark lower level. Once again, you can only continue east or west.", 
  "A discord of wild noises, belonging mostly to prowling animals, resonated through the air, and added to the sounds of the rustling of the leaves and branches of the tree tops in the wind. Finally you can go in a different direction, to the north.",
  "The forest was small, dense, and verdant. Its canopy was reigned by magnolia, hazel, and sequoia, and sparkling light dancing between the branches allowed for vibrant shrubs to take advantage of the moss covered grounds below. The only opening is to the west or back south to where you just came from.",
  "Bundled creepers drooped from the occasional tree, and a range of flowers, which grew all over the place, contrasted against the otherwise brown and green terrain. The only way forward is to the west.", 
  "Thick tree limbs grasped many trees, and a variety of flowers, which grew in a sprinkled and disorderly fashion, spruced up the otherwise dark lower level. The only opening ahead is to the west or back east.",
  "A hodgepodge of wild sounds, belonging mostly to foraging animals, reverberated through the air, and formed a chaotic orchestra with the swaying of tree tops in the wind. The only opening is still to the west or back east.",
  "The forest was colossal, impenetrable, and flourishing. Its canopy was ruled by hazel, juniper, and buxus, and abundant dancing lights bounced through their crowns for a flood of ferns to dominate the sloping and slanting ground below. You can only continue west or east.",
  "Swooping vines hung from every tree, and a variety of flowers, which desperately tried to avoid the shadows, highlighted the otherwise unvarying scenery. Why can I only go west or back east?", 
  "A mixture of animal noises, most belonged to critters, added life to the forest, and drowned out the occasional roar of a large animal trying to scare away predators. Only path lies westwards and eastwards.",
  "The forest was huge, spacious, and rich. Its canopy was eclipsed by spruce, magnolia, and larch, and abundant dancing lights bounced through their crowns for a medley of herbs to grow in the moist and fertile bottom layer below. West is the only way available forward to you.", 
  "Thick tree limbs grasped many trees, and a variety of flowers, which grew in a sprinkled and disorderly fashion, spruced up the otherwise dark lower level. Once again, you can only continue ahead to the west.", 
  "A discord of wild noises, belonging mostly to prowling animals, resonated through the air, and added to the sounds of the rustling of the leaves and branches of the tree tops in the wind. Finally you can go in a different direction, to the north.",
  "The forest was small, dense, and verdant. Its canopy was reigned by magnolia, hazel, and sequoia, and sparkling light dancing between the branches allowed for vibrant shrubs to take advantage of the moss covered grounds below. The only opening is to the east or back west.",
  "Bundled creepers drooped from the occasional tree, and a range of flowers, which grew all over the place, contrasted against the otherwise brown and green terrain. The only opening is to the east or back west.", 
  "Thick tree limbs grasped many trees, and a variety of flowers, which grew in a sprinkled and disorderly fashion, spruced up the otherwise dark lower level. The only opening is to the east or west.",
  "A hodgepodge of wild sounds, belonging mostly to foraging animals, reverberated through the air, and formed a chaotic orchestra with the swaying of tree tops in the wind. The only opening is still to the east or west.",
  "The forest was colossal, impenetrable, and flourishing. Its canopy was ruled by hazel, juniper, and buxus, and abundant dancing lights bounced through their crowns for a flood of ferns to dominate the sloping and slanting ground below. You can only continue eastwards or back westwards.",
  "Swooping vines hung from every tree, and a variety of flowers, which desperately tried to avoid the shadows, highlighted the otherwise unvarying scenery. Why can I only go east or west?", 
  "A mixture of animal noises, most belonged to critters, added life to the forest, and drowned out the occasional roar of a large animal trying to scare away predators. Only path lies eastwards or westwards.",
  "The forest was huge, spacious, and rich. Its canopy was eclipsed by spruce, magnolia, and larch, and abundant dancing lights bounced through their crowns for a medley of herbs to grow in the moist and fertile bottom layer below. Once again, the only directions available are east or west.", 
  "Thick tree limbs grasped many trees, and a variety of flowers, which grew in a sprinkled and disorderly fashion, spruced up the otherwise dark lower level. Once again, you can only continue east or west.", 
  "A discord of wild noises, belonging mostly to prowling animals, resonated through the air, and added to the sounds of the rustling of the leaves and branches of the tree tops in the wind. Finally you can go in a different direction, to the north.",
  "The forest was small, dense, and verdant. Its canopy was reigned by magnolia, hazel, and sequoia, and sparkling light dancing between the branches allowed for vibrant shrubs to take advantage of the moss covered grounds below. The only opening is to the west or back south to where you just came from.",
  "Bundled creepers drooped from the occasional tree, and a range of flowers, which grew all over the place, contrasted against the otherwise brown and green terrain. The only way forward is to the west.", 
  "Thick tree limbs grasped many trees, and a variety of flowers, which grew in a sprinkled and disorderly fashion, spruced up the otherwise dark lower level. The only opening ahead is to the west or back east.",
  "A hodgepodge of wild sounds, belonging mostly to foraging animals, reverberated through the air, and formed a chaotic orchestra with the swaying of tree tops in the wind. The only opening is still to the west or back east.",
  "The forest was colossal, impenetrable, and flourishing. Its canopy was ruled by hazel, juniper, and buxus, and abundant dancing lights bounced through their crowns for a flood of ferns to dominate the sloping and slanting ground below. You can only continue west or east.",
  "Swooping vines hung from every tree, and a variety of flowers, which desperately tried to avoid the shadows, highlighted the otherwise unvarying scenery. Why can I only go west or back east?", 
  "A mixture of animal noises, most belonged to critters, added life to the forest, and drowned out the occasional roar of a large animal trying to scare away predators. Only path lies westwards and eastwards.",
  "The forest was huge, spacious, and rich. Its canopy was eclipsed by spruce, magnolia, and larch, and abundant dancing lights bounced through their crowns for a medley of herbs to grow in the moist and fertile bottom layer below. West is the only way available forward to you.", 
  "Thick tree limbs grasped many trees, and a variety of flowers, which grew in a sprinkled and disorderly fashion, spruced up the otherwise dark lower level. Once again, you can only continue ahead to the west.", 
  "A discord of wild noises, belonging mostly to prowling animals, resonated through the air, and added to the sounds of the rustling of the leaves and branches of the tree tops in the wind. Finally you can go in a different direction, to the north.",
  "The forest was small, dense, and verdant. Its canopy was reigned by magnolia, hazel, and sequoia, and sparkling light dancing between the branches allowed for vibrant shrubs to take advantage of the moss covered grounds below. The only opening is to the east or back west.",
  "Bundled creepers drooped from the occasional tree, and a range of flowers, which grew all over the place, contrasted against the otherwise brown and green terrain. The only opening is to the east or back west.", 
  "Thick tree limbs grasped many trees, and a variety of flowers, which grew in a sprinkled and disorderly fashion, spruced up the otherwise dark lower level. The only opening is to the east or west.",
  "A hodgepodge of wild sounds, belonging mostly to foraging animals, reverberated through the air, and formed a chaotic orchestra with the swaying of tree tops in the wind. The only opening is still to the east or west.",
  "The forest was colossal, impenetrable, and flourishing. Its canopy was ruled by hazel, juniper, and buxus, and abundant dancing lights bounced through their crowns for a flood of ferns to dominate the sloping and slanting ground below. You can only continue eastwards or back westwards.",
  "Swooping vines hung from every tree, and a variety of flowers, which desperately tried to avoid the shadows, highlighted the otherwise unvarying scenery. Why can I only go east or west?", 
  "A mixture of animal noises, most belonged to critters, added life to the forest, and drowned out the occasional roar of a large animal trying to scare away predators. Only path lies eastwards or westwards.",
  "The forest was huge, spacious, and rich. Its canopy was eclipsed by spruce, magnolia, and larch, and abundant dancing lights bounced through their crowns for a medley of herbs to grow in the moist and fertile bottom layer below. Once again, the only directions available are east or west.", 
  "Thick tree limbs grasped many trees, and a variety of flowers, which grew in a sprinkled and disorderly fashion, spruced up the otherwise dark lower level. Once again, you can only continue east or west.", 
  "A discord of wild noises, belonging mostly to prowling animals, resonated through the air, and added to the sounds of the rustling of the leaves and branches of the tree tops in the wind. Finally you can go in a different direction, to the north.",
  "The forest was small, dense, and verdant. Its canopy was reigned by magnolia, hazel, and sequoia, and sparkling light dancing between the branches allowed for vibrant shrubs to take advantage of the moss covered grounds below. The only opening is to the west or back south to where you just came from.",
  "Bundled creepers drooped from the occasional tree, and a range of flowers, which grew all over the place, contrasted against the otherwise brown and green terrain. The only way forward is to the west.", 
  "Thick tree limbs grasped many trees, and a variety of flowers, which grew in a sprinkled and disorderly fashion, spruced up the otherwise dark lower level. The only opening ahead is to the west or back east.",
  "A hodgepodge of wild sounds, belonging mostly to foraging animals, reverberated through the air, and formed a chaotic orchestra with the swaying of tree tops in the wind. The only opening is still to the west or back east.",
  "The forest was colossal, impenetrable, and flourishing. Its canopy was ruled by hazel, juniper, and buxus, and abundant dancing lights bounced through their crowns for a flood of ferns to dominate the sloping and slanting ground below. You can only continue west or east.",
  "Swooping vines hung from every tree, and a variety of flowers, which desperately tried to avoid the shadows, highlighted the otherwise unvarying scenery. Why can I only go west or back east?", 
  "A mixture of animal noises, most belonged to critters, added life to the forest, and drowned out the occasional roar of a large animal trying to scare away predators. Only path lies westwards and eastwards.",
  "The forest was huge, spacious, and rich. Its canopy was eclipsed by spruce, magnolia, and larch, and abundant dancing lights bounced through their crowns for a medley of herbs to grow in the moist and fertile bottom layer below. West is the only way available forward to you.", 
  "Thick tree limbs grasped many trees, and a variety of flowers, which grew in a sprinkled and disorderly fashion, spruced up the otherwise dark lower level. Once again, you can only continue ahead to the west.", 
  "A discord of wild noises, belonging mostly to prowling animals, resonated through the air, and added to the sounds of the rustling of the leaves and branches of the tree tops in the wind. You reach what seems to be a dead end. You notice a strange bush in the corner and look behind it and see an ancient wooden door with strange runes carved on it.  This must be where the treasure lies!"
]
