# Generated by Django 3.0.2 on 2020-01-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200123_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='z',
            field=models.IntegerField(default=0),
        ),
    ]
